app:
  name: ochat
  document: ""
  env: dev # dev、test、product

server:
  host: 127.0.0.1
  port: 8080
  scheme: http

avatar:
  file_dir: /files/static/avatar/default/
  uri: /files/avatar/
  suffix_name: .png
  default_avatar: avatar_boy_male_user_young_icon
  upload_dir: /files/upload/avatar/

login_qrcode:
  file_dir: /files/upload/login_qrcode
  uri: /files/qrcode/
  suffix_name: .png
